opt_in_rules: # some rules are only opt-in
- contains_over_filter_count

disabled_rules: # rule identifiers to exclude from running
- colon
- trailing_whitespace
- comma
- line_length
- orphaned_doc_comment
- switch_case_alignment
- identifier_name
- function_body_length
#- file_length
#- type_body_length
- todo
#- function_parameter_count
- force_cast
- large_tuple
- force_try

line_length:
- 150 # warning
- 200 # error
ignores_comments: true
ignores_urls: true

file_length:
- 550
- 1200
ignore_comment_only_lines: true

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
severity: warning # explicitly

# they can set both implicitly with an array
type_body_length:
- 300 # warning
- 500 # error
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
min_length: 4 # only warning
max_length: # warning and error
warning: 40
error: 50
#
identifier_name:
min_length: # only min_length
warning: 4 # only error

function_parameter_count:
warning: 6
error: 8

cyclomatic_complexity:
warning: 10
error: 25
